### PR TITLE
Hao/config network

### PR DESCRIPTION
**Pull request by leomayleomay**
Closes
https://github.com/ArdanaLabs/cardano-app-template/issues/10

other changes

- [ ] The impure tests via `nix run .#offchain:test` were run and all are passing.
- [ ] Where applicable, grammar, punctuation, and spelling within code and comments should be plausibly correct.
- [ ] The issue(s) that the work is addressing should be linked in the PR description.
- [ ] Any significant changes beyond what's clear from the linked issue(s) are documented in the PR description

### CODE REVIEW

**Review by epiro-ps — CHANGES_REQUESTED** [review]
Could you see if it's possible to pass the network config directly in from Nami so that the UI doesn't need to require the user to select the network twice?

**Comment by leomayleomay** [comment]
> Could you see if it's possible to pass the network config directly in from Nami so that the UI doesn't need to require the user to select the network twice?

sure thing, will do

**Comment by leomayleomay** [comment]
@EvanPiro I am wondering what the UI should do if the user changes the network after locking the funds?

**Comment by epiro-ps** [comment]
> @EvanPiro I am wondering what the UI should do if the user changes the network after locking the funds?

The app should refresh/reset, clearing the state. If the user wants to see if they have funds that they can redeem on the network they just connected to, they'll need to press the resume button.

**Review by epiro-ps — APPROVED** [review]
Solid work. Browser testing passes on my end.

**Pull request merged**
